Feature/cypress test
10up/Ad-Refresh-Control pull request #148
Opened 2024-06-17 10:15 UTC by sudip-md

### Description of the Change
I have added test cases for Ad-Refresh-Control plugin and it is working fine in local.

Where possible, please also include:
- Please Make sure, you have properly setup Ad-Refresh-Control plugin in you local
- Test Is working fine in local
![image](https://github.com/10up/Ad-Refresh-Control/assets/94599521/bf6cc8cd-69fe-4525-b1b5-2e52bf4669ee)

-->

### How to test the Change
Please setup plugin in loca

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2024-06-18 07:12 UTC, Sidsector9 requested changes

2024-06-18 07:12 UTC, Sidsector9 commented on .github/workflows/cypress.yml
> +jobs:
Thanks for working on this @sudip-md 

For the pipeline, we run the tests on the release ZIP. You can refer to how we're doing it in other plugins such as [Restricted Site Access ](https://github.com/10up/restricted-site-access/blob/develop/.github/workflows/cypress.yml) and [Simple Local Avatars](https://github.com/10up/simple-local-avatars/blob/develop/.github/workflows/cypress.yml).

2024-10-16 00:53 UTC, jeffpaul commented on .github/workflows/cypress.yml
> +jobs:
@Sidsector9 probably best if you can help update this and get merged in

2025-03-13 16:17 UTC, jeffpaul commented on .github/workflows/cypress.yml
> +jobs:
@Sidsector9 FYI that I branched #168 off this PR to hopefully help resolve your concerns here.  If that looks good, go ahead and review/merge 168 and then we can proceed with the PR here.

2025-03-17 10:24 UTC, Sidsector9 approved these changes

2025-03-17 10:25 UTC, merged

2025-03-21 21:20 UTC, dkotter commented
Just a note here that it seems E2E tests were not working coming out of this PR and #168. There's a failing test but more importantly, the tests weren't even working properly due to multiple issues (things like `mochawesome` not existing, trying to run a script that didn't even exist, etc). I've fixed those issues on #172 but there's still a failing test I've marked as skipped for now as it needs additional work.

Noting this mostly as a reminder that we shouldn't merge PRs in that aren't actually fully functional, as we just end up having to spend time down the line fixing those issues on unrelated PRs.